name: CI/CD — build & deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry (DockerHub or GitHub Container Registry)
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/ai-agent:latest

  deploy:
    name: Deploy to DigitalOcean
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & deploy to Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/ai-agent:latest
            docker stop ai-agent || true
            docker rm ai-agent || true
            docker run -d --name ai-agent -p 80:8080 your-dockerhub-username/ai-agent:latest
